/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: '#fcf9f8',
        'on-background': '#1c1b1b',
        surface: '#fcf9f8',
        'on-surface': '#1c1b1b',
        'surface-variant': '#e5e2e1',
        'on-surface-variant': '#544245',
        primary: '#983d54',
        'on-primary': '#ffffff',
        secondary: '#755b00',
        'on-secondary': '#ffffff',
        'matte-black': '#1c1b1b',
        'warm-cream': '#fcf9f8',
        gold: '#755b00',
        'deep-rose': '#983d54',
        
        // Stitch design system tokens
        'surface-container-lowest': '#ffffff',
        'on-tertiary-fixed': '#1e1b18',
        'tertiary-fixed-dim': '#cbc5c1',
        'on-tertiary': '#ffffff',
        'surface-tint': '#9b4056',
        'tertiary-fixed': '#e8e1dc',
        'on-error-container': '#93000a',
        'primary-container': '#b6556c',
        'error-container': '#ffdad6',
        'on-secondary-fixed': '#241a00',
        'on-secondary-fixed-variant': '#584400',
        'on-primary-container': '#fffbff',
        error: '#ba1a1a',
        'on-primary-fixed': '#3f0016',
        'primary-fixed': '#ffd9de',
        'inverse-primary': '#ffb1c0',
        'surface-container-highest': '#e5e2e1',
        'surface-bright': '#fcf9f8',
        'secondary-fixed-dim': '#e6c364',
        'outline-variant': '#dac0c3',
        'on-error': '#ffffff',
        tertiary: '#5f5b58',
        'surface-container-high': '#eae7e7',
        'surface-container': '#f0eded',
        'inverse-surface': '#313030',
        'on-tertiary-container': '#fffbff',
        'on-secondary-container': '#785d00',
        outline: '#877275',
        'secondary-container': '#fed977',
        'on-primary-fixed-variant': '#7d283f',
        'secondary-fixed': '#ffe08f',
        'tertiary-container': '#787470',
        'primary-fixed-dim': '#ffb1c0',
        'surface-dim': '#dcd9d9',
        'surface-container-low': '#f6f3f2',
        'inverse-on-surface': '#f3f0ef',
        'on-tertiary-fixed-variant': '#4a4643',
      },
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        serif: ['Playfair Display', 'ui-serif', 'Georgia', 'serif'],
      },
      spacing: {
        'margin-mobile': '20px',
        'margin-desktop': '64px',
        'stack-sm': '8px',
        'stack-md': '24px',
        'stack-lg': '48px',
        'section-gap': '96px',
        'gutter': '24px',
      },
    },
  },
  plugins: [],
}
